/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	globalArgc = argc;
	globalArgv = argv;


	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	
	printLine("Calling CWE415_Double_Free__malloc_free_char_01_good();");
	CWE415_Double_Free__malloc_free_char_01_good();

	printLine("Calling CWE415_Double_Free__malloc_free_char_01_bad();");
	CWE415_Double_Free__malloc_free_char_01_bad();


	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	


	return 0;

} 
